version: '3'

services:
    etcd-1:
        container_name: etcd1
        image: quay.io/coreos/etcd:v3.4.15
        entrypoint: /usr/local/bin/etcd
        command:
            - '--name=etcd-1'
            - '--initial-advertise-peer-urls=http://etcd-1:2380'
            - '--listen-peer-urls=http://0.0.0.0:2380'
            - '--listen-client-urls=http://0.0.0.0:2379'
            - '--advertise-client-urls=http://etcd-1:2379'
            - '--initial-cluster-token=mys3cr3ttok3n'
            - '--heartbeat-interval=250'
            - '--election-timeout=1250'
            - '--initial-cluster=etcd-1=http://etcd-1:2380'
            - '--initial-cluster-state=new'
        ports:
            - "2379:2379"
        volumes:
            - ./store/etcd1/data:/etcd-1.etcd
