version: "3"

services:
  jenkins:
    build: ./jenkins_use
    container_name: jenkins
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/aico/test/jenkins/jenkins_mount:/var/jenkins_home
      - /home/aico/test/jenkins/jenkins_use/.ssh/:/root/.ssh/
      - /usr/bin/yarn:/usr/bin/yarn
    ports:
      - "10240:8080"
      - "50000:50000"
