pipeline {
    agent any
    environment {
        GIT_COMMIT_MSG = sh (script: 'git log --no-walk --format=format:%s ${GIT_COMMIT}', returnStdout: true).trim()
        WEBUI_NAME = "nas_ui" //部署应用名称
        DEPLOYMENT_PATH = "/www/nas"
    }
    stages {
        // 打印commit message
        stage("commit print"){
           steps{
               sh "echo $GIT_COMMIT_MSG"
           }
        }
        // 部署nas_ui
        stage("nas_ui build"){
            steps{
                script{
                    //只部署
                    if (env.GIT_COMMIT_MSG == "nas_ui"){
                        sh "rm -fr $DEPLOYMENT_PATH/*"
                        sh "cp -r dist/* $DEPLOYMENT_PATH/"
                    }
                }
            }
        }
    }
}
